# Generated by Django 3.2 on 2024-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_title_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='slug',
        ),
    ]
