# Generated by Django 3.2 on 2024-07-13 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240712_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Идентификатор; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+\\- ]+$')], verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(verbose_name='Год произведения'),
        ),
    ]
