# Generated by Django 3.2 on 2024-07-17 06:29

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validators.validation_year], verbose_name='Год произведения'),
        ),
    ]
