# Generated by Django 3.2 on 2024-07-17 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20240717_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Оценка не выше 10!'), django.core.validators.MinValueValidator(1, message='Оценка не ниже 1!')]),
        ),
    ]
