# Generated by Django 3.2 on 2024-07-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20240713_2144'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='UniqueReviewConstraint',
        ),
    ]
