# Generated by Django 3.2 on 2024-07-16 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Оценка не может быть выше 10!'), django.core.validators.MinValueValidator(1, message='Оценка не может быть ниже 1!')]),
        ),
    ]
